import type { Flag, ChangeRequest, AuditEvent } from './types'

const now = new Date().toISOString()
const actor = 'system'

const createAudit = (flagId: string, env: 'staging' | 'production', value: boolean | string): AuditEvent[] => [
  {
    id: `${flagId}-create-${env}`,
    flagId,
    environment: env,
    action: 'create',
    oldValue: '',
    newValue: value,
    actor,
    timestamp: now,
  },
]

export const initialFlags: Flag[] = [
  {
    id: 'flag-1',
    key: 'new-onboarding-flow',
    name: 'New onboarding flow',
    description: 'Simplified three-step onboarding experiment for mobile sign-ups.',
    type: 'boolean',
    stagingValue: true,
    productionValue: false,
    sensitive: false,
    owner: 'Product — Growth',
    updatedAt: now,
    auditLog: createAudit('flag-1', 'staging', true).concat(createAudit('flag-1', 'production', false)),
  },
  {
    id: 'flag-2',
    key: 'plaid-link-v2',
    name: 'Plaid Link v2 integration',
    description: 'Use Plaid Link v2 for account linking and micro-deposit fallback.',
    type: 'boolean',
    stagingValue: true,
    productionValue: true,
    sensitive: false,
    owner: 'Engineering — Connections',
    updatedAt: now,
    auditLog: createAudit('flag-2', 'staging', true).concat(createAudit('flag-2', 'production', true)),
  },
  {
    id: 'flag-3',
    key: 'instant-withdrawal',
    name: 'Instant withdrawal',
    description: 'Allow users to move funds to a linked debit card within minutes.',
    type: 'boolean',
    stagingValue: true,
    productionValue: false,
    sensitive: true,
    owner: 'Product — Payments',
    updatedAt: now,
    auditLog: createAudit('flag-3', 'staging', true).concat(createAudit('flag-3', 'production', false)),
  },
  {
    id: 'flag-4',
    key: 'wire-fee-promo',
    name: 'Wire fee promotional pricing',
    description: 'Promotional wire-transfer fee schedule for the SMB launch.',
    type: 'enum',
    options: ['standard', 'discounted', 'waived'],
    stagingValue: 'discounted',
    productionValue: 'standard',
    sensitive: true,
    owner: 'Revenue — Treasury',
    updatedAt: now,
    auditLog: createAudit('flag-4', 'staging', 'discounted').concat(createAudit('flag-4', 'production', 'standard')),
  },
  {
    id: 'flag-5',
    key: 'high-value-auth-step-up',
    name: 'Step-up auth for high-value transfers',
    description: 'Require additional MFA for transfers above the configured risk threshold.',
    type: 'boolean',
    stagingValue: true,
    productionValue: true,
    sensitive: true,
    owner: 'Security — Fraud',
    updatedAt: now,
    auditLog: createAudit('flag-5', 'staging', true).concat(createAudit('flag-5', 'production', true)),
  },
  {
    id: 'flag-6',
    key: 'kyc-document-ai',
    name: 'AI-powered KYC document review',
    description: 'Route uploaded identity documents through the ML document classifier.',
    type: 'boolean',
    stagingValue: true,
    productionValue: false,
    sensitive: false,
    owner: 'Compliance — KYC',
    updatedAt: now,
    auditLog: createAudit('flag-6', 'staging', true).concat(createAudit('flag-6', 'production', false)),
  },
  {
    id: 'flag-7',
    key: 'interest-rate-display',
    name: 'Show live interest rate banner',
    description: 'Control where the live APY banner appears in the app.',
    type: 'enum',
    options: ['hidden', 'banner', 'full'],
    stagingValue: 'full',
    productionValue: 'banner',
    sensitive: false,
    owner: 'Marketing — Engagement',
    updatedAt: now,
    auditLog: createAudit('flag-7', 'staging', 'full').concat(createAudit('flag-7', 'production', 'banner')),
  },
  {
    id: 'flag-8',
    key: 'p2p-transfers',
    name: 'Peer-to-peer transfers',
    description: 'Send money to friends and family using a phone number or handle.',
    type: 'boolean',
    stagingValue: true,
    productionValue: false,
    sensitive: true,
    owner: 'Product — Payments',
    updatedAt: now,
    auditLog: createAudit('flag-8', 'staging', true).concat(createAudit('flag-8', 'production', false)),
  },
  {
    id: 'flag-9',
    key: 'fraud-realtime-scoring',
    name: 'Real-time fraud scoring',
    description: 'Enable real-time scoring engine on authorization requests.',
    type: 'boolean',
    stagingValue: false,
    productionValue: true,
    sensitive: true,
    owner: 'Security — Fraud',
    updatedAt: now,
    auditLog: createAudit('flag-9', 'staging', false).concat(createAudit('flag-9', 'production', true)),
  },
  {
    id: 'flag-10',
    key: 'crypto-buy-flow',
    name: 'Cryptocurrency purchase flow',
    description: 'New regulated crypto purchase flow with disclosures and custody warnings.',
    type: 'boolean',
    stagingValue: true,
    productionValue: false,
    sensitive: true,
    owner: 'Product — Crypto',
    updatedAt: now,
    auditLog: createAudit('flag-10', 'staging', true).concat(createAudit('flag-10', 'production', false)),
  },
]

export const initialRequests: ChangeRequest[] = [
  {
    id: 'req-1',
    flagId: 'flag-3',
    environment: 'production',
    requestedValue: true,
    previousValue: false,
    requestedBy: 'sarah.chen',
    requestedAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    reason: 'Enable instant withdrawals for Platinum SMB accounts during the launch window.',
    status: 'pending',
  },
]
